name: Flutter CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Step 1: Check out the repository
    - name: Checkout repository
      uses: actions/checkout@v2

    # Step 2: Set up Flutter
    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: 'stable'

    # Step 3: Install dependencies
    - name: Install dependencies
      run: flutter pub get
      working-directory: workspaces/pc2/pc_app

    # Step 4: Run tests
    - name: Run tests
      run: flutter test
      working-directory: workspaces/pc2/pc_app

    # Step 5: Build the app (optional, for example APK or IPA)
    - name: Build APK
      run: flutter build apk --release
      working-directory: workspaces/pc2/pc_app

    # Step 6: Upload build artifacts
    - name: Upload APK artifact
      uses: actions/upload-artifact@v3
      with:
        name: app-release-apk
        path: workspaces/pc2/pc_app/build/app/outputs/flutter-apk/app-release.apk
